nginx:
  user: www www
  worker_processes: 5
  error_log: logs/error.log
  pid: logs/nginx.pid
  worker_rlimit_nofile: 8192
  events:
    worker_connections: 4096
  http:
    includes:
      - conf/mime.types
      - /etc/nginx/proxy.conf
      - /etc/nginx/fastcgi.conf
    index: [index.html, index.htm, index.php]
    default_type: application/octet-stream
    log_format:
      main: '$remote_addr - $remote_user [$time_local]  $status "$request" $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"'
    access_log:
      path: logs/access.log
      format: main
    sendfile: on
    tcp_nopush: on
    server_names_hash_bucket_size: 128
    servers:
      - name: php/fastcgi
        listen: 80
        server_name: [domain1.com, www.domain1.com]
        access_log:
          path: logs/domain1.access.log
          format: main
        root: html
        locations:
          - match: \.php$
            fastcgi_pass: 127.0.0.1:1025
      - name: simple reverse-proxy
        listen: 80
        server_name: [domain2.com, www.domain2.com]
        access_log:
          path: logs/domain2.access.log
          format: main
        locations:
          - match: ^/(images|javascript|js|css|flash|media|static)/
            root: /var/www/virtual/big.server.com/htdocs
            expires: 30d
          - match: /
            proxy_pass: http://127.0.0.1:8080
      - name: simple load balancing
        listen: 80
        server_name: big.server.com
        access_log:
          path: logs/big.server.access.log
          format: main
        locations:
          - match: /
            proxy_pass: http://big_server_com
    upstream:
      big_server_com:
        servers:
          - address: 127.0.0.3:8000
            weight: 5
          - address: 127.0.0.3:8001
            weight: 5
          - address: 192.168.0.1:8000
          - address: 192.168.0.1:8001
