server:
  port: 8080
  host: 127.0.0.1
  server_name: 127.0.0.1
  error_page:
    301: ./websites/err_page/301.html
    404: ./websites/err_page/404.html
  limit_client_body: 1M
  root: ./websites
  loaction: /
    methods: GET PUT DELETE
    root: /
  loaction: /test
    methods: GET PUT DELETE
    root: /test_page
    directory_listing: on
    index: index.html

server:
  port: 8080
  host: 127.0.0.1
  server_name: localhost
  root: ./websites
  loaction: /
    methods: GET PUT DELETE
    root: /

server:
  port: 8081
  host: 127.0.0.1
  server_name: localhost
  root: ./websites
  loaction: /
    methods: GET PUT DELETE
    root: /

